# Generated by Django 3.2.4 on 2022-05-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(choices=[('Instrumentos de cuerdas', 'Cuerdas'), ('Instrumentos de percusión', 'Percusión'), ('Amplificadores para instrumentos', 'Amplificadores'), ('Accesorios varios para variados instrumentos', 'Accesorios varios')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('stock', models.PositiveBigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSubCategory', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDetalle', models.CharField(max_length=30)),
                ('nivel', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.category')),
                ('producto', models.ManyToManyField(to='tienda.Product')),
                ('subCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.sub_category')),
            ],
        ),
    ]
