# Generated by Django 3.2.4 on 2022-05-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
