# Generated by Django 3.2.4 on 2022-05-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_product_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_categoria',
            name='producto',
        ),
        migrations.AddField(
            model_name='product',
            name='detalle',
            field=models.ManyToManyField(to='tienda.detalle_Categoria'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.category'),
        ),
    ]
