# Generated by Django 3.2.4 on 2022-05-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20220518_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
