# Generated by Django 3.2.4 on 2022-05-19 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_categoria',
            old_name='nameDetalle',
            new_name='nombre',
        ),
    ]
