# Generated by Django 3.2.4 on 2022-05-19 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_rename_namedetalle_detalle_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detalle',
        ),
        migrations.AddField(
            model_name='product',
            name='detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.detalle_categoria'),
        ),
    ]
